config/routes.rb
Rails.application.routes.draw do
  
  # get 'mixtapes/new'
  # get 'mixtapes/create'
  # get 'mixtapes/index'
  # get 'mixtapes/show'
  # get 'mixtapes/edit'
  # get 'mixtapes/update'
  # get 'mixtapes/destroy'
  root to: 'pages#home'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' =>'session#destroy'  #Destroy session(log out)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :mixtapes
end

app/models/album.rb
class Album < ApplicationRecord
    has_many :songs
    has_many :artists, through: 'songs'


    #Model own helpers
    def artist
        self.artists.uniq.first #Assumption is that there actually is only one artist per album 
    end #artist()


    # def print_nicely
    #     " '#{self.title}' by #{self.artist.name } "
    # end

    #Automatically ruby will look for this method if not defined it will print result by the default method
    #Equivalent of what we have above print_nicely
    def to_s
        " '#{self.title}' by #{self.artist.name } "
    end

    def song_titles
        self.songs.pluck(:title).join(" - ")
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :songs
    #Free Association - No extra joining table or ids require due 
    #Due to songs relationships songs -> genres, songs-> albums 
    #Songs being the in-between model
    has_many :genres, through: 'songs' #Could also be written like a symbool :songs'
    has_many :mixtapes, through: 'songs'
    has_many :albums, through: 'songs'
end

app/models/genre.rb
class Genre < ApplicationRecord
     #This define one end of a many to many relationships
     #it requires that "genre_songs" join table exists,
     #and the table should have genre_id and song_id
     has_and_belongs_to_many :songs
end

app/models/mixtape.rb
class Mixtape < ApplicationRecord
    has_and_belongs_to_many :songs
    belongs_to :user, optional: true
    #validates :name, length:{ minimum: 2, maximum: 20}
end

app/models/song.rb
class Song < ApplicationRecord
    belongs_to :artist, optional: true
    belongs_to :album, optional: true
    has_and_belongs_to_many :genres
    has_and_belongs_to_many :mixtapes
end

app/models/user.rb
class User < ApplicationRecord
    #Use the bcrypt gem to encrypt password, at the point of creating a new user object in the DB
    #And store only the encrypted version
    has_secure_password
    has_many  :mixtapes

    validates :email, presence: true, uniqueness: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :fetch_user

    def fetch_user 
        if session[:user_id].present?
            @current_user = User.find_by id: session[:user_id]
        end
        session[:user_id] = nil unless @current_user.present?
    end 

    def check_if_logged_in
        unless @current_user.present?
            flash[:error] = "You must  be logged in u sneaky bitch!"
            redirect_to login_path
        end
    end

end

app/controllers/mixtapes_controller.rb
class MixtapesController < ApplicationController
  before_action :check_if_logged_in, except: [:index, :show]
  def new
    @mixtape = Mixtape.new
  end

  def create
    @mixtape = Mixtape.new mixtape_params
    @mixtape.user_id = @current_user.id
    @mixtape.save
    if  @mixtape.persisted?
      redirect_to mixtapes_path    
    else
      render :new                                                                                                                                                
    end
  end

  def index
     @mixtapes = Mixtape.all
  end

  def show
  end

  def edit
    @mixtape = Mixtape.find params[:id]
    redirect_to login_path unless @mixtape.user_id == @current_user.id 
  end

  def update
    @mixtape = Mixtape.find  params[:id]
    #Don't perform the edit on this item if the ids don't match
    if @mixtape.user_id != @current_user.id #Trying to edit something that's from its user
        return redirect_to login_path 
    end
    if @mixtape.update mixtape_params
      redirect_to mixtape_path(@mixtape.id)
    else
      render :edit
    end
  
  end

  def destroy
  end

  private def mixtape_params
    params.require(:mixtape).permit(:name, :iamge)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  

  def home
    fetch_user
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
      #1 Check if email entered is in the db at all
      user = User.find_by email: params[:email]
      if user.present? && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to root_path
      else
        #Either user was nill or invalid password
        redirect_to login_path
        flash[:error] = "Bad Credentials, try again."
      end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mixtapes_helper.rb
module MixtapesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TunrDb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body style="background-color:#000; color:#fff">
    <nav>
      <h1>
        Tunr Music Database
      </h1>
      <% if @current_user.present? %>
          Welcome, <%= @current_user.name %>
          |
          <%= link_to "Logout", login_path, method: 'delete' %>
          |
          <%= link_to "Create Mixtape", new_mixtape_path %>
      <% else %>
        <%= link_to "Login", login_path %>
        |
        <%= link_to "Sing up", '' %>
      <% end %>
      |
        <%= link_to "Mixtapes", mixtapes_path %>
      <hr>
    </nav>

    <%= yield %>
  </body>
  <footer>
    <hr>
  </footer>
</html>

app/views/mixtapes/_form.html.erb
<% if @mixtape.errors.any? %>
    <% @mixtape.errors.full_messages.each do |el| %>
        <li>
            <%=el %>
        </li>
    <% end %>
<% end %>

<%= form_with model: @mixtape, local:true do |f| %>
<%= f.label :name %>
<br>
<%= f.text_field :name%>
<br><br>
<%= f.submit %>

<% end %>

app/views/mixtapes/create.html.erb
<h1>Mixtapes#create</h1>
<p>Find me in app/views/mixtapes/create.html.erb</p>

app/views/mixtapes/destroy.html.erb
<h1>Mixtapes#destroy</h1>
<p>Find me in app/views/mixtapes/destroy.html.erb</p>

app/views/mixtapes/edit.html.erb
<h1> Edit Mixtape: <%= @mixtape.name  %></h1>

<%= render partial: 'form' %>

app/views/mixtapes/index.html.erb
<h2> All Mixtapes </h2>

<ul>

    <% @mixtapes.each do |mix| %>
    <li>
        <%= link_to mix.name, mixtape_path(mix.id) %>
        <% if @current_user.present? &&  mix.user_id == @current_user.id %>
            (<%= link_to "Edit", edit_mixtape_path(mix.id) %>)
        <% end %>
    </li>
    <% end %>
</ul>

app/views/mixtapes/new.html.erb
<h1>New Mixtape </h1>
<%= render partial: 'form' %>

app/views/mixtapes/show.html.erb
<h1>Mixtapes#show</h1>
<p>Find me in app/views/mixtapes/show.html.erb</p>

app/views/mixtapes/update.html.erb
<h1>Mixtapes#update</h1>
<p>Find me in app/views/mixtapes/update.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>

    <% if @current_user.present? %>
        <h3>Welcome ser: <%= @current_user.name %> </h3>
    <% end %>
</p>

app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

app/views/session/new.html.erb
<h2>Login</h2>

<%# we can use the form_with helper for generic forms that do not correspond to a model
to do this we use a diferent syntax, we use 'url:some url here' instead of model @model %>
<% if flash[:error] %>

        <strong> <%=  flash[:error] %></strong>
<% end %>
<%= form_with url: login_path, local: true do |f|  %>
    <%= f.label :email %>
    <br>
    <%= f.text_field :email %>
    <br><br>
    <%= f.label :password %>
    <br>
    <%= f.password_field :password %>
    <br><br>
    <%= f.submit  "Login" %>
<% end %>
<br>